# Generated by Django 4.2.7 on 2023-12-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='usuario/user-default.png', null=True, upload_to='usuario'),
        ),
    ]
