# Generated by Django 4.2.7 on 2023-12-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='img/user-default.png', null=True, upload_to='usuario'),
        ),
    ]
